// <auto-generated />
namespace Projet_examen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class premier_migation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(premier_migation));
        
        string IMigrationMetadata.Id
        {
            get { return "202502261344121_premier_migation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
